# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Mapping Los Angeles Murals
description: "This is a site about murals in Los Angeles."
baseurl: ""
url: "https://muralcartographies.github.io/MuralsofLA/"
twitter_username: andy_rutkowski
github_username:  andy_rutkowski
email_username:  arutkows@usc.edu

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
