# Site settings
title: Mapping Los Angeles Murals
header-img: img.home-bg.jpg
email: arutkowski@library.ucla.edu
copyright_name: MappingLosAngelesMurals
description: "This project maps mural collections from across the Los Angeles area, including UCLA and USC"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: andy_rutkowski
github_username:  andyrutkowskiucla

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
